<!DOCTYPE html>
<html>
<?php
//HEAD
include_once(INCLUDES.DS.'main_head.php'); 
?>  
<body> 
<?php
//HEADER
include_once(INCLUDES.DS.'main_header.php'); 
?>
<div data-gracket='[
   [
      [
         {
            "name":"jQuery",
            "id":"jquery"
         },
         {
            "name":"MooTools",
            "id":"mootools"
         }
      ],
      [
         {
            "name":"extjs",
            "id":"extjs",
            "seed":10
         },
         {
            "name":"jqueryui",
            "id":"jqueryui",
            "seed":14
         }
      ]
   ],
   [
      [
         {
            "name":"jQuery",
            "id":"jquery",
            "seed":1
         },
         {
            "name":"extjs",
            "id":"extjs",
            "seed":10
         }
      ]
   ],
   [
      [
         {
            "name":"jQuery",
            "id":"jquery",
            "seed":1
         }
      ]
   ]
]' class="container-fluid paddAll">
</div>
<?php
//FOOTER
include_once(INCLUDES.DS.'main_footer.php'); 
?>    
</body>
</html>